/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AuthenticatedSerieIdRouteImport } from './routes/_authenticated/serie.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSerieIdRoute = AuthenticatedSerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/': typeof AuthenticatedIndexRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/serie/$id': typeof AuthenticatedSerieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/trending' | '/watchlist' | '/serie/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/trending' | '/watchlist' | '/' | '/serie/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/trending'
    | '/_authenticated/watchlist'
    | '/_authenticated/'
    | '/_authenticated/serie/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serie/$id': {
      id: '/_authenticated/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof AuthenticatedSerieIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSerieIdRoute: typeof AuthenticatedSerieIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSerieIdRoute: AuthenticatedSerieIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
