/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedWatchedRouteImport } from './routes/_authenticated/watched'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedSerieIdRouteImport } from './routes/_authenticated/serie.$id'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person.$id'
import { Route as AuthenticatedMovieIdRouteImport } from './routes/_authenticated/movie.$id'
import { Route as AuthenticatedListIdRouteImport } from './routes/_authenticated/list.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchedRoute = AuthenticatedWatchedRouteImport.update({
  id: '/watched',
  path: '/watched',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSerieIdRoute = AuthenticatedSerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovieIdRoute = AuthenticatedMovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListIdRoute = AuthenticatedListIdRouteImport.update({
  id: '/list/$id',
  path: '/list/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/import': typeof AuthenticatedImportRoute
  '/social': typeof AuthenticatedSocialRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/watched': typeof AuthenticatedWatchedRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/list/$id': typeof AuthenticatedListIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/import': typeof AuthenticatedImportRoute
  '/social': typeof AuthenticatedSocialRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/watched': typeof AuthenticatedWatchedRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/': typeof AuthenticatedIndexRoute
  '/list/$id': typeof AuthenticatedListIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/serie/$id': typeof AuthenticatedSerieIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/_authenticated/watched': typeof AuthenticatedWatchedRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/list/$id': typeof AuthenticatedListIdRoute
  '/_authenticated/movie/$id': typeof AuthenticatedMovieIdRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/_authenticated/serie/$id': typeof AuthenticatedSerieIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/import'
    | '/social'
    | '/stats'
    | '/trending'
    | '/watched'
    | '/watchlist'
    | '/list/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/serie/$id'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/import'
    | '/social'
    | '/stats'
    | '/trending'
    | '/watched'
    | '/watchlist'
    | '/'
    | '/list/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/serie/$id'
    | '/u/$username'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/import'
    | '/_authenticated/social'
    | '/_authenticated/stats'
    | '/_authenticated/trending'
    | '/_authenticated/watched'
    | '/_authenticated/watchlist'
    | '/_authenticated/'
    | '/_authenticated/list/$id'
    | '/_authenticated/movie/$id'
    | '/_authenticated/person/$id'
    | '/_authenticated/serie/$id'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watched': {
      id: '/_authenticated/watched'
      path: '/watched'
      fullPath: '/watched'
      preLoaderRoute: typeof AuthenticatedWatchedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serie/$id': {
      id: '/_authenticated/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof AuthenticatedSerieIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movie/$id': {
      id: '/_authenticated/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof AuthenticatedMovieIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list/$id': {
      id: '/_authenticated/list/$id'
      path: '/list/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof AuthenticatedListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
  AuthenticatedWatchedRoute: typeof AuthenticatedWatchedRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedListIdRoute: typeof AuthenticatedListIdRoute
  AuthenticatedMovieIdRoute: typeof AuthenticatedMovieIdRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
  AuthenticatedSerieIdRoute: typeof AuthenticatedSerieIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
  AuthenticatedWatchedRoute: AuthenticatedWatchedRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedListIdRoute: AuthenticatedListIdRoute,
  AuthenticatedMovieIdRoute: AuthenticatedMovieIdRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
  AuthenticatedSerieIdRoute: AuthenticatedSerieIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
